### ISSUE TITLE
Catch all Exceptions

### ISSUE THREAD

**Issue by giorizzotti** [instagrambot/instapy-cli#39]
Hi, I want to catch all exceptions of your library.
I'm trying with:
`except Exception as e:
`
but doesn't works. If I'm not wrong, there is no example in your repository.

What can I use? 
Thank you and sorry for bothering you in these days.

**Comment by b3nab** [comment]
Hi @giorizzotti ,
please post an example code. As well as this is a python related issue, I think you can search on stackoverflow for a better related answer.

The python way do accomplish what you want is:
```python
try:
   # your code that raise exceptions
except:
   # bad way to manage exceptions
finally:
   # finally do what you want after the try block and eventually exception
```

I suggest to search on stackoverflow, here you will find a related question with many useful and detailed answers [About catching ANY Exception](https://stackoverflow.com/questions/4990718/about-catching-any-exception)
