### ISSUE TITLE
pip instructions failed

### ISSUE THREAD

**Issue by vitorgalvao** [instagrambot/instapy-cli#40]
Following the [install instructions](https://github.com/b3nab/instapy-cli#install):

> pip install instapy-cli

I got

> Could not find a version that satisfies the requirement instagram-private-api-extensions==0.3.8 (from instapy-cli) (from versions: )
No matching distribution found for instagram-private-api-extensions==0.3.8 (from instapy-cli)

So I went to [`instagram-private-api-extensions`’s page](https://github.com/ping/instagram_private_api) and followed [their instructions](https://github.com/ping/instagram_private_api#install):

> pip install git+https://git@github.com/ping/instagram_private_api.git@1.6.0

I had to do the same with `instagram-private-api`, and then `instapy-cli` installed fine. However, those two packages [should have been installed automatically](https://github.com/b3nab/instapy-cli#this-packages-will-be-installed-automatically-with-instapy-cli).

Python `3.7.2` on macOS `10.14.4`.

**Comment by provisionalideas** [comment]
I'm having this same issue, except that I installed instagram-private-api and instagram-private-api-extensions using the methods above, and am still getting
`Could not find a version that satisfies the requirement instagram-private-api-extensions==0.3.8 (from instapy-cli) (from versions: )
No matching distribution found for instagram-private-api-extensions==0.3.8 (from instapy-cli)`
when I try to 
`pip install instapy-cli`
Any advice would be appreciated!

**Comment by vitorgalvao** [comment]
@provisionalideas Include your OS name and version, as well as your Python version, otherwise @b3nab has no way to debug your issue.

**Comment by othmane53** [comment]
@provisionalideas same problem !
help please

**Comment by vitorgalvao** [comment]
> @provisionalideas same problem !
help please

As I said:

> Include your OS name and version, as well as your Python version, otherwise @b3nab has no way to debug your issue.

**Comment by namanyayg** [comment]
Got the same error, very strange since documentation explicitly says "packages will be installed automatically". @vitorgalvao has the correct fix, installing both `instagram_private_api` and `instagram_private_api_extensions` and then `pip install instapy-cli` worked.

@provisionalideas did you install [`instagram_private_api_extensions`](https://github.com/ping/instagram_private_api_extensions#install) correctly?

**Comment by b3nab** [comment]
I'm releasing an hot fix.
Please update your instapy-cli version to 0.0.9.2
🥂
