### ISSUE TITLE
Don’t create config file in same directory where script it run

### ISSUE THREAD

**Issue by vitorgalvao** [instagrambot/instapy-cli#41]
By creating the [`ig.json`](https://github.com/b3nab/instapy-cli/blob/936de73c942999d0ceb5ae44cf9bc03337669b29/instapy_cli/cli.py#L11) wherever the script is run, `instapy-cli` is polluting the user’s system (likely the home) and not taking advantage of the config if it already exists in another directory.

The config file should be stored in a fixed location, either following the XDG Base Directory specification, or at the very least in the fixed `~/.config/instapy-ci/ig.json`.

**Comment by vitorgalvao** [comment]
@b3nab The new commit doesn’t fix this issue.

[The README’s hint](https://github.com/instagrambot/instapy-cli/tree/4e545c2cf93867f836be951762b44b240174bc1f#hint) requires the user to mess around with the script, which is not a friendly interface. My proposed solution would be seamless. Alternatively, a CLI flag to use/save the JSON from/to a specific location would also work, while retaining the ability to have several in the system.

For anyone that stumbles on this, the workaround I’m using is to always move to a specific directory before running the tool:

```bash
config_dir="${HOME}/.config/instapy-cli"
[[ -d "${config_dir}" ]] || mkdir -p "${config_dir}"
cd "${config_dir}" || exit 1
```

**Comment by b3nab** [comment]
@vitorgalvao 
Please reopen a new issue and use the correct template.
