### ISSUE TITLE
[BUG] Installation Error

### ISSUE THREAD

**Issue by Wolgrand** [instagrambot/instapy-cli#48]
**Describe the bug**
After the command pip install instapy-cli an error occurs:

Collecting instagram-private-api-extensions==0.3.8 (from instapy-cli)
  ERROR: Could not find a version that satisfies the requirement instagram-private-api-extensions==0.3.8 (from instapy-cli) (from versions: none)
ERROR: No matching distribution found for instagram-private-api-extensions==0.3.8 (from instapy-cli)

**To Reproduce**
pip install instapy-cli

```python
pip install instapy-cli
```

**Expected behavior**
Was expected to install instapy-cli
**Logs**
Collecting instagram-private-api-extensions==0.3.8 (from instapy-cli)
  ERROR: Could not find a version that satisfies the requirement instagram-private-api-extensions==0.3.8 (from instapy-cli) (from versions: none)
ERROR: No matching distribution found for instagram-private-api-extensions==0.3.8 (from instapy-cli)
```

```

**Env (please complete the following information):**
 -WIndows
 - Python: [e.g. 3.7]
 - instapy-cli Version: [e.g. 0.0.9.0]

**Comment by Wolgrand** [comment]
Issue already reported from another user.

**Comment by b3nab** [comment]
Please check latest version `0.0.10`. From now on we won't have no more problem with these two packages `instagram-private-api` and `instagram-private-api-extensions`. I released just some minutes ago these ones on PyPi, so everyone from now on will be able to download `instapy-cli v. 0.0.10` and use it without headache during the installation process.

🥂
